import {requireUser,nav,toast,logout} from "./navigation.js";import {db} from "./firebase.js";import {ref,push,set,get,remove,update,onValue} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-database.js";import {compressImage} from "./imageCompression.js";
const verified=u=>u?.verified?'<img class="verified" src="https://raw.githubusercontent.com/7lbsaa1/assets/main/facebook-verified.png" onerror="this.style.display=\'none\'" alt="موثق">':"";
const esc=s=>(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let current,posts={};
function postCard(p,u){return `<article class="post-card glass" data-id="${p.id}"><div class="post-head"><img class="avatar" src="${u.profileImage||'https://via.placeholder.com/80'}" alt=""><div class="post-meta"><strong>${esc(u.name)} ${verified(u)}</strong><small>@${esc(u.username)} · ${new Date(p.createdAt).toLocaleString('ar-EG')}</small></div><button class="post-menu">•••</button></div>${p.caption?`<p class="caption">${esc(p.caption)}</p>`:""}<img class="post-image" loading="lazy" src="${p.imageBase64}" alt="منشور sky7"><div class="stats"><span>${p.likesCount||0} إعجاب</span><span>${p.commentsCount||0} تعليق · ${p.sharesCount||0} مشاركة</span></div><div class="actions"><button data-action="like">♡ أعجبني</button><button data-action="comment">💬 تعليق</button><button data-action="share">↗ مشاركة</button><button data-action="save">🔖 حفظ</button></div></article>`}
async function render(){current=await requireUser();const u=current.data;document.getElementById("app").innerHTML=nav(u)+`<main class="layout"><aside class="left-side side-card glass"><div class="person"><img class="avatar" src="${u.profileImage||''}"><div>${esc(u.name)} ${verified(u)}<small class="muted">مرحبًا بك مجددًا</small></div></div><nav class="menu"><a class="active" href="home.html">الصفحة الرئيسية</a><a href="profile.html">الملف الشخصي</a><a href="favorite.html">الصور المحفوظة</a><a href="users.html">الأصدقاء / المستخدمون</a><a href="admin.html">الإدارة</a><a href="#" id="logout">تسجيل الخروج</a></nav></aside><section class="feed"><div class="create-card glass"><div class="create-top"><img class="avatar" src="${u.profileImage||''}"><button class="create-open" id="openCreate">ماذا في بالك؟ انشر صورة من السماء أو الطبيعة...</button></div></div><div id="feed"><div class="loading-screen">جاري تحميل المنشورات...</div></div></section><aside class="right-section glass"><h3>الأصدقاء المتصلون</h3><div class="muted">لا توجد بيانات إضافية حاليًا.</div></aside></main>`;document.getElementById("logout").onclick=e=>{e.preventDefault();logout()};document.getElementById("openCreate").onclick=openCreate;loadPosts()}
async function loadPosts(){onValue(ref(db,"posts"),async snap=>{const box=document.getElementById("feed");posts=snap.val()||{};const arr=Object.entries(posts).map(([id,p])=>({...p,id})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,30);const html=[];for(const p of arr){const s=await get(ref(db,"users/"+p.userId));html.push(postCard(p,s.exists()?s.val():{name:"مستخدم",username:"user"}))}box.innerHTML=html.join("")||'<div class="post-card glass">لا توجد منشورات حتى الآن.</div>';box.querySelectorAll("[data-action='like']").forEach(b=>b.onclick=()=>like(b));box.querySelectorAll("[data-action='save']").forEach(b=>b.onclick=()=>save(b));box.querySelectorAll("[data-action='comment']").forEach(b=>b.onclick=()=>comment(b));})}
async function like(btn){const id=btn.closest(".post-card").dataset.id;const r=ref(db,`reactions/${id}/${current.auth.uid}`);const s=await get(r);if(s.exists())return;await set(r,{type:"like",createdAt:Date.now()});const p=posts[id];await update(ref(db,"posts/"+id),{likesCount:(p.likesCount||0)+1});btn.textContent="♥ تم الإعجاب"}
async function save(btn){const id=btn.closest(".post-card").dataset.id;await set(ref(db,`favorites/${current.auth.uid}/${id}`),{savedAt:Date.now()});toast("تم حفظ المنشور.")}
function comment(btn){const id=btn.closest(".post-card").dataset.id;const text=prompt("اكتب تعليقك:");if(!text)return;const r=push(ref(db,`comments/${id}`));set(r,{userId:current.auth.uid,text,createdAt:Date.now()}).then(()=>toast("تم إضافة التعليق."))}
function openCreate(){const b=document.createElement("div");b.className="modal-backdrop";b.innerHTML=`<section class="modal glass"><div class="modal-head"><h2>نشر صورة</h2><button class="close">×</button></div><label>الصورة<input id="postFile" type="file" accept="image/*"></label><img id="preview" class="preview hidden"><label>الوصف<textarea id="caption" rows="4" maxlength="1000" placeholder="اكتب وصف الصورة..."></textarea></label><button class="primary-btn" id="publish">نشر الصورة</button></section>`;document.body.append(b);b.querySelector(".close").onclick=()=>b.remove();b.querySelector("#postFile").onchange=async e=>{if(e.target.files[0]){preview.src=await compressImage(e.target.files[0]);preview.classList.remove("hidden")}};b.querySelector("#publish").onclick=async()=>{if(!preview.src)return toast("اختر صورة أولًا.");const r=push(ref(db,"posts"));await set(r,{id:r.key,userId:current.auth.uid,caption:caption.value||"",imageBase64:preview.src,createdAt:Date.now(),likesCount:0,commentsCount:0,sharesCount:0});toast("تم نشر الصورة.");b.remove()}}
render();